### ISSUE TITLE
Player isn´s premium

### ISSUE THREAD

**Issue by Rub3nuak** [MrIvanPlays/Skins#5]
The plugin was working good until I installed Mcmmo and the plugin didnt work any more, it says player isn´t premium even tho it worked before. I uninstalled mcmmo but still not working. I reinstalled 3 times, even tried with the Skin-17 beta. The same message every player i put

**Comment by MrIvanPlays** [comment]
Try resetting the plugin's data and running it without plugins

**Comment by Rub3nuak** [comment]
What do you mean reseat the plugin data?

**Comment by MrIvanPlays** [comment]
Delete the "Skins" folder in your plugins folder

**Comment by Rub3nuak** [comment]
Did that twice still not working...

**Comment by MrIvanPlays** [comment]
May I know your java version?

**Comment by Rub3nuak** [comment]
Could it be something related to internet connection?

**Comment by MrIvanPlays** [comment]
It can, also it can be that if you're running java 14 cuz java 14 has https issues.

**Comment by Rub3nuak** [comment]
version 1.8.0 I think

**Comment by MrIvanPlays** [comment]
I need confirmation, not "I think"

**Comment by Rub3nuak** [comment]
Is it the on the about java tab?

**Comment by Rub3nuak** [comment]
I´ll try restarting my pc

**Comment by MrIvanPlays** [comment]
If you're on a hosting company, ask them about your java version.
If you're on a VPS, get in ssh session and run `java -version`
If you're localhost, open your terminal and type `java -version`

**Comment by Rub3nuak** [comment]
java version "1.8.0_251"

**Comment by MrIvanPlays** [comment]
Will check

**Comment by Rub3nuak** [comment]
For some reason your skin works....
tried with famous youtuber and didnt work

**Comment by Rub3nuak** [comment]
Now doesn´t work with you skin either

**Comment by Rub3nuak** [comment]
And it works again now.....
But only with your skin

**Comment by Rub3nuak** [comment]
Now works with mine
Is the skin server down or something??

**Comment by MrIvanPlays** [comment]
You may get ratelimited, I've fixed an issue with initial join skin set I'm going to push the commit now, but

I cannot reproduce the issue you're explaining to me using paper-283 (version 1.15.2) with mcMMO version 2.1.129-SNAPSHOT

**Comment by Rub3nuak** [comment]
Im using spigot but its fine if it works for now...

**Comment by MrIvanPlays** [comment]
I'd recommend you to try reproducing the issue on the latest dev build, also wait about 20 minutes before trying it out so you do not hit mojang's rate limits.
